version: "3.3"
services:
  rc_db:
    image: postgres
    environment:
      POSTGRES_DB: "rc_db"
      POSTGRES_USER: "bpm"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  cache:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
  db:
    driver: local
