version: "3.3"
services:
  rc_db:
    image: postgres
    environment:
      POSTGRES_DB: "rc_db"
      POSTGRES_USER: "bpm"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local

